# Example configuration with one validator and one full node
# Todo: document this fully
[global]
gaiad_binary="$GOPATH/bin/gaiad"
ports_start_at=27000
home_dir="$HOME/.gm"
auto_maintain_config=true
comment="Please add comments to all node definitions. (Mandatory.)"

[validator1]
comment="This is a validator with global defaults."

[node1]
comment="This is a full node that attaches to validator1."
network="validator1"
