[global]
strategy = 'packets'
filter = false
log_level = 'info'
clear_packets_interval = 100

# Toggle the transaction confirmation mechanism.
# The tx confirmation mechanism periodically queries the `/tx_search` RPC
# endpoint to check that previously-submitted transactions
# (to any chain in this config file) have delivered successfully.
# Experimental feature. Affects telemetry if set to false.
# Default: true.
tx_confirmation = true


# The REST section defines parameters for Hermes' built-in RESTful API.
# https://hermes.informal.systems/rest.html
[rest]
enabled = true
host = '127.0.0.1'
port = 3000
[telemetry]
enabled = true
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'celo-1'
rpc_addr = 'http://127.0.0.1:26558'
websocket_addr = 'ws://127.0.0.1:26658/websocket'
rpc_timeout = '10s'
code_id = '22889a91243b66f65c414ea69ef20291d030649f3e0cf667b57c18bfe9fa03e3'
client_contract_address : web3::types::Address,
client_contract_abi_json: PathBuf,
handler_contract_address : web3::types::Address,
handler_contract_abi_json: PathBuf,
host_contract_address : web3::types::Address,
host_contract_abi_json: PathBuf,
account_prefix = 'celo'
key_name = 'relayer'
store_prefix = 'ibc'
max_gas = 3000000000
max_tx_size = 2097152
gas_price = { price = 0.001, denom = 'stake' }

allowed_clock_skew: u64,
trusting_period: u64,
upgrade_path: Vec<String>,
verify_epoch_headers: bool,
verify_non_epoch_headers: bool,
verify_header_timestamp: bool,
allow_update_after_misbehavior: bool,
allow_update_after_expiry: bool,
account_prefix = 'cosmos'
address_type = { derivation = 'cosmos' }
gas_adjustment = 0.1
max_msg_num = 30
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
//Celo light client state
epoch_size: u64,
allowed_clock_skew: u64,
trusting_period: u64,
upgrade_path: Vec<String>,
verify_epoch_headers: bool,
verify_non_epoch_headers: bool,
verify_header_timestamp: bool,
allow_update_after_misbehavior: bool,
allow_update_after_expiry: bool,
epoch_size = 17280
allowed_clock_skew = 5
trusting_period = 10
upgrade_path = []
verify_epoch_headers = true
verify_non_epoch_headers = true
verify_header_timestamp = true
allow_update_after_misbehavior = true
allow_update_after_expiry = true


[[chains]]
id = 'cosmos-1'
rpc_addr = 'http://127.0.0.1:26657'
grpc_addr = 'http://127.0.0.1:9090'
websocket_addr = 'ws://127.0.0.1:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'relayer'
store_prefix = 'ibc'
max_gas = 30000000000
gas_price = { price = 0.001, denom = 'stake' }
gas_adjustment = 0.1
max_msg_num = 30
max_tx_size = 2097152
clock_drift = '5s'
trusting_period = '14days'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
